import { useState, useEffect } from 'react'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts'
import jsPDF from 'jspdf'

const growthStages = [
  'Seedling',
  'Tillering',
  'Stem Elongation',
  'Booting',
  'Heading',
  'Flowering',
  'Milk Stage',
  'Dough Stage',
  'Maturity',
]

const purposes = [
  'Yield Maximization',
  'Cost Optimization',
  'Soil Health',
  'Balanced Growth',
  'Organic Farming',
]

// Storage key for history
const HISTORY_STORAGE_KEY = 'fertilizer_recommendation_history'

// Mock API function - replace with actual API call
const fetchFertilizerRecommendation = async (sensorData, growthStage, purpose) => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 1500))
  
  // Mock response structure matching expected Python ML API
  return {
    top3: [
      {
        rank: 1,
        fertilizer: 'NPK 16-16-16',
        quantity: 140,
        predictedYield: 7.2,
        confidence: 92,
      },
      {
        rank: 2,
        fertilizer: 'Urea + DAP Mix',
        quantity: 100,
        predictedYield: 6.8,
        confidence: 87,
      },
      {
        rank: 3,
        fertilizer: 'Organic Compost Blend',
        quantity: 200,
        predictedYield: 6.5,
        confidence: 82,
      },
    ],
  }
}

// Download report function - PDF format
const downloadReport = (record) => {
  const doc = new jsPDF()
  let yPosition = 20

  // Header
  doc.setFontSize(18)
  doc.setTextColor(34, 197, 94) // Green color
  doc.text('AI-Based Fertilizer Recommendation Report', 105, yPosition, { align: 'center' })
  yPosition += 10

  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)
  doc.text(`Report ID: ${record.id}`, 20, yPosition)
  yPosition += 7
  doc.text(`Date: ${record.date}`, 20, yPosition)
  yPosition += 7
  doc.text(`Time: ${record.time}`, 20, yPosition)
  yPosition += 7
  doc.text(`Mode: ${record.sensorMode === 'real-time' ? 'Real-time Sensor Data' : 'Manual Input'}`, 20, yPosition)
  yPosition += 15

  // Sensor Data Section
  doc.setFontSize(14)
  doc.setTextColor(34, 197, 94)
  doc.text('Sensor Data', 20, yPosition)
  yPosition += 8

  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)
  doc.text(`Soil Temperature: ${record.sensorData.soilTemperature}°C`, 25, yPosition)
  yPosition += 7
  doc.text(`Soil Moisture: ${record.sensorData.soilMoisture}%`, 25, yPosition)
  yPosition += 7
  doc.text(`Air Temperature: ${record.sensorData.airTemperature}°C`, 25, yPosition)
  yPosition += 7
  doc.text(`Air Humidity: ${record.sensorData.airHumidity}%`, 25, yPosition)
  yPosition += 15

  // User Input Section
  doc.setFontSize(14)
  doc.setTextColor(34, 197, 94)
  doc.text('User Input', 20, yPosition)
  yPosition += 8

  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)
  doc.text(`Growth Stage: ${record.userInput.growthStage}`, 25, yPosition)
  yPosition += 7
  doc.text(`Purpose: ${record.userInput.purpose}`, 25, yPosition)
  yPosition += 15

  // Recommendations Section
  doc.setFontSize(14)
  doc.setTextColor(34, 197, 94)
  doc.text('Top 3 Fertilizer Recommendations', 20, yPosition)
  yPosition += 10

  // Table Header
  doc.setFontSize(10)
  doc.setFont(undefined, 'bold')
  doc.text('Rank', 25, yPosition)
  doc.text('Fertilizer', 50, yPosition)
  doc.text('Quantity', 110, yPosition)
  doc.text('Yield', 140, yPosition)
  doc.text('Confidence', 170, yPosition)
  yPosition += 7

  // Draw line
  doc.setDrawColor(200, 200, 200)
  doc.line(20, yPosition - 2, 190, yPosition - 2)
  yPosition += 5

  // Table Rows
  doc.setFont(undefined, 'normal')
  record.recommendations.forEach((item, index) => {
    if (yPosition > 270) {
      doc.addPage()
      yPosition = 20
    }

    doc.text(item.rank.toString(), 25, yPosition)
    doc.text(item.fertilizer, 50, yPosition)
    doc.text(`${item.quantity} kg/acre`, 110, yPosition)
    doc.text(`${item.predictedYield} ton/ha`, 140, yPosition)
    doc.text(`${item.confidence}%`, 170, yPosition)
    yPosition += 7

    // Draw line between rows
    if (index < record.recommendations.length - 1) {
      doc.setDrawColor(240, 240, 240)
      doc.line(20, yPosition - 2, 190, yPosition - 2)
      yPosition += 3
    }
  })

  yPosition += 10

  // Footer
  if (yPosition > 250) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text('Generated by AI-Based Fertilizer Recommendation System', 105, yPosition, { align: 'center' })
  yPosition += 5
  doc.text(`Report generated on ${new Date().toLocaleString()}`, 105, yPosition, { align: 'center' })

  // Save PDF
  const fileName = `fertilizer-report-${record.id}.pdf`
  doc.save(fileName)
}

// Load history from localStorage
const loadHistory = () => {
  try {
    const stored = localStorage.getItem(HISTORY_STORAGE_KEY)
    return stored ? JSON.parse(stored) : []
  } catch (error) {
    console.error('Error loading history:', error)
    return []
  }
}

// Save to localStorage (simulating database)
const saveToHistory = (record) => {
  try {
    const history = loadHistory()
    const newHistory = [record, ...history] // Add new record at the beginning
    localStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(newHistory))
    return true
  } catch (error) {
    console.error('Error saving history:', error)
    return false
  }
}

export default function FertilizerRecommendation() {
  // Tab state
  const [activeTab, setActiveTab] = useState('recommendation') // 'recommendation' or 'history'

  // Sensor Mode Toggle
  const [sensorMode, setSensorMode] = useState(true) // true = real-time, false = manual

  // Live Sensor Readings State
  const [sensorData, setSensorData] = useState({
    soilTemperature: 28.5,
    soilMoisture: 65,
    airTemperature: 32.2,
    airHumidity: 75,
  })

  // Manual Input State (when sensor mode is OFF)
  const [manualInputs, setManualInputs] = useState({
    soilTemperature: '',
    soilMoisture: '',
    airTemperature: '',
    airHumidity: '',
  })

  // User Input State
  const [growthStage, setGrowthStage] = useState('')
  const [purpose, setPurpose] = useState('')

  // Results State
  const [results, setResults] = useState(null)
  const [loading, setLoading] = useState(false)
  const [saved, setSaved] = useState(false)

  // History State
  const [history, setHistory] = useState([])

  // Load history on component mount
  useEffect(() => {
    setHistory(loadHistory())
  }, [])

  // Simulate live sensor updates (only when sensor mode is ON)
  useEffect(() => {
    if (!sensorMode || activeTab !== 'recommendation') return

    const interval = setInterval(() => {
      setSensorData((prev) => ({
        soilTemperature: parseFloat((parseFloat(prev.soilTemperature) + (Math.random() - 0.5) * 0.5).toFixed(1)),
        soilMoisture: Math.max(40, Math.min(80, Math.round(prev.soilMoisture + (Math.random() - 0.5) * 2))),
        airTemperature: parseFloat((parseFloat(prev.airTemperature) + (Math.random() - 0.5) * 0.5).toFixed(1)),
        airHumidity: Math.max(60, Math.min(90, Math.round(prev.airHumidity + (Math.random() - 0.5) * 2))),
      }))
    }, 3000)

    return () => clearInterval(interval)
  }, [sensorMode, activeTab])

  const handleManualInputChange = (field, value) => {
    setManualInputs((prev) => ({ ...prev, [field]: value }))
  }

  const getCurrentSensorData = () => {
    if (sensorMode) {
      return sensorData
    } else {
      return {
        soilTemperature: parseFloat(manualInputs.soilTemperature) || 0,
        soilMoisture: parseFloat(manualInputs.soilMoisture) || 0,
        airTemperature: parseFloat(manualInputs.airTemperature) || 0,
        airHumidity: parseFloat(manualInputs.airHumidity) || 0,
      }
    }
  }

  const handleGenerateRecommendation = async () => {
    if (!growthStage || !purpose) {
      return
    }

    // Validate manual inputs if sensor mode is OFF
    if (!sensorMode) {
      if (
        !manualInputs.soilTemperature ||
        !manualInputs.soilMoisture ||
        !manualInputs.airTemperature ||
        !manualInputs.airHumidity
      ) {
        return
      }
    }

    setLoading(true)
    setSaved(false)
    try {
      const currentData = getCurrentSensorData()
      const recommendation = await fetchFertilizerRecommendation(currentData, growthStage, purpose)
      setResults(recommendation)
    } catch (error) {
      // Silent error handling - no error messages displayed
      console.error('Error fetching recommendation:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleSavePrediction = () => {
    if (!results) return

    const currentData = getCurrentSensorData()
    const now = new Date()
    const record = {
      id: `rec_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      timestamp: now.toISOString(),
      date: now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
      time: now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', second: '2-digit' }),
      sensorMode: sensorMode ? 'real-time' : 'manual',
      sensorData: currentData,
      userInput: {
        growthStage: growthStage,
        purpose: purpose,
      },
      recommendations: results.top3,
    }

    if (saveToHistory(record)) {
      setSaved(true)
      setHistory(loadHistory()) // Refresh history
      setTimeout(() => setSaved(false), 3000) // Reset saved message after 3 seconds
    }
  }

  const handleDownloadReport = (record = null) => {
    if (record) {
      // Download from history
      downloadReport(record)
    } else if (results) {
      // Download current prediction
      const currentData = getCurrentSensorData()
      const now = new Date()
      const reportRecord = {
        id: `temp_${Date.now()}`,
        timestamp: now.toISOString(),
        date: now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
        time: now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', second: '2-digit' }),
        sensorData: currentData,
        userInput: {
          growthStage: growthStage,
          purpose: purpose,
        },
        recommendations: results.top3,
      }
      downloadReport(reportRecord)
    }
  }

  // Prepare chart data
  const barChartData = results?.top3
    ? results.top3.map((item) => ({
        fertilizer: item.fertilizer,
        yield: item.predictedYield,
      }))
    : []

  const confidenceData = results?.top3
    ? results.top3.map((item) => ({
        name: item.fertilizer,
        value: item.confidence,
        color: item.rank === 1 ? '#22c55e' : item.rank === 2 ? '#3b82f6' : '#f59e0b',
      }))
    : []

  const currentSensorData = getCurrentSensorData()
  const canGenerate = sensorMode
    ? growthStage && purpose
    : growthStage && purpose && manualInputs.soilTemperature && manualInputs.soilMoisture && manualInputs.airTemperature && manualInputs.airHumidity

  return (
    <div className="space-y-8">
      {/* 1. Page Header */}
      <div className="bg-white rounded-lg shadow-md p-6">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">
          AI-Based Fertilizer Recommendation System
        </h1>
        <p className="text-lg text-gray-600">
          Sensor-based AI decision support system for optimal fertilizer recommendations and yield prediction.
          The system analyzes real-time sensor data or manual inputs along with crop growth stage and farming purpose to provide
          personalized fertilizer recommendations with predicted yield outcomes.
        </p>
      </div>

      {/* Tab Navigation */}
      <div className="bg-white rounded-lg shadow-md">
        <div className="border-b border-gray-200">
          <nav className="flex space-x-8 px-6" aria-label="Tabs">
            <button
              onClick={() => setActiveTab('recommendation')}
              className={`py-4 px-1 border-b-2 font-medium text-sm ${
                activeTab === 'recommendation'
                  ? 'border-agri-green-500 text-agri-green-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              Recommendation
            </button>
            <button
              onClick={() => setActiveTab('history')}
              className={`py-4 px-1 border-b-2 font-medium text-sm ${
                activeTab === 'history'
                  ? 'border-agri-green-500 text-agri-green-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              History ({history.length})
            </button>
          </nav>
        </div>
      </div>

      {/* Recommendation Tab Content */}
      {activeTab === 'recommendation' && (
        <>
          {/* Sensor Mode Toggle */}
          <div className="bg-white rounded-lg shadow-md p-6">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-1">IoT Sensor Connection</h2>
                <p className="text-sm text-gray-600">
                  {sensorMode
                    ? 'Real-time sensor data is being used for predictions'
                    : 'Manual input mode - enter sensor values manually'}
                </p>
              </div>
              <div className="flex items-center space-x-3">
                <span className={`text-sm font-medium ${!sensorMode ? 'text-gray-900' : 'text-gray-500'}`}>
                  Manual
                </span>
                <button
                  type="button"
                  onClick={() => setSensorMode(!sensorMode)}
                  className={`relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-agri-green-500 focus:ring-offset-2 ${
                    sensorMode ? 'bg-agri-green-600' : 'bg-gray-200'
                  }`}
                  role="switch"
                  aria-checked={sensorMode}
                >
                  <span
                    className={`pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${
                      sensorMode ? 'translate-x-5' : 'translate-x-0'
                    }`}
                  />
                </button>
                <span className={`text-sm font-medium ${sensorMode ? 'text-gray-900' : 'text-gray-500'}`}>
                  Real-time
                </span>
              </div>
            </div>
          </div>

          {/* 2. Sensor Readings / Manual Input Section */}
          <div className="bg-white rounded-lg shadow-md p-6">
            <h2 className="text-xl font-bold text-gray-900 mb-4">
              {sensorMode ? 'Live Sensor Readings' : 'Manual Sensor Input'}
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              {sensorMode ? (
                // Real-time Sensor Cards
                <>
                  <div className="bg-agri-green-50 border-l-4 border-agri-green-500 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-2xl">🌡️</span>
                      <span className="text-xs text-gray-500 bg-white px-2 py-1 rounded">Live</span>
                    </div>
                    <p className="text-sm font-medium text-gray-600">Soil Temperature</p>
                    <p className="text-2xl font-bold text-gray-900 mt-1">{sensorData.soilTemperature}°C</p>
                  </div>

                  <div className="bg-blue-50 border-l-4 border-blue-500 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-2xl">💧</span>
                      <span className="text-xs text-gray-500 bg-white px-2 py-1 rounded">Live</span>
                    </div>
                    <p className="text-sm font-medium text-gray-600">Soil Moisture</p>
                    <p className="text-2xl font-bold text-gray-900 mt-1">{sensorData.soilMoisture}%</p>
                  </div>

                  <div className="bg-orange-50 border-l-4 border-orange-500 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-2xl">🌡️</span>
                      <span className="text-xs text-gray-500 bg-white px-2 py-1 rounded">Live</span>
                    </div>
                    <p className="text-sm font-medium text-gray-600">Air Temperature</p>
                    <p className="text-2xl font-bold text-gray-900 mt-1">{sensorData.airTemperature}°C</p>
                  </div>

                  <div className="bg-cyan-50 border-l-4 border-cyan-500 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-2xl">☁️</span>
                      <span className="text-xs text-gray-500 bg-white px-2 py-1 rounded">Live</span>
                    </div>
                    <p className="text-sm font-medium text-gray-600">Air Humidity</p>
                    <p className="text-2xl font-bold text-gray-900 mt-1">{sensorData.airHumidity}%</p>
                  </div>
                </>
              ) : (
                // Manual Input Fields
                <>
                  <div>
                    <label htmlFor="manualSoilTemp" className="block text-sm font-medium text-gray-700 mb-2">
                      Soil Temperature (°C)
                    </label>
                    <input
                      type="number"
                      id="manualSoilTemp"
                      value={manualInputs.soilTemperature}
                      onChange={(e) => handleManualInputChange('soilTemperature', e.target.value)}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-agri-green-500 focus:border-agri-green-500"
                      placeholder="e.g., 28.5"
                      step="0.1"
                    />
                  </div>

                  <div>
                    <label htmlFor="manualSoilMoisture" className="block text-sm font-medium text-gray-700 mb-2">
                      Soil Moisture (%)
                    </label>
                    <input
                      type="number"
                      id="manualSoilMoisture"
                      value={manualInputs.soilMoisture}
                      onChange={(e) => handleManualInputChange('soilMoisture', e.target.value)}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-agri-green-500 focus:border-agri-green-500"
                      placeholder="e.g., 65"
                      min="0"
                      max="100"
                    />
                  </div>

                  <div>
                    <label htmlFor="manualAirTemp" className="block text-sm font-medium text-gray-700 mb-2">
                      Air Temperature (°C)
                    </label>
                    <input
                      type="number"
                      id="manualAirTemp"
                      value={manualInputs.airTemperature}
                      onChange={(e) => handleManualInputChange('airTemperature', e.target.value)}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-agri-green-500 focus:border-agri-green-500"
                      placeholder="e.g., 32.2"
                      step="0.1"
                    />
                  </div>

                  <div>
                    <label htmlFor="manualAirHumidity" className="block text-sm font-medium text-gray-700 mb-2">
                      Air Humidity (%)
                    </label>
                    <input
                      type="number"
                      id="manualAirHumidity"
                      value={manualInputs.airHumidity}
                      onChange={(e) => handleManualInputChange('airHumidity', e.target.value)}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-agri-green-500 focus:border-agri-green-500"
                      placeholder="e.g., 75"
                      min="0"
                      max="100"
                    />
                  </div>
                </>
              )}
            </div>
          </div>

          {/* 3. User Input Section */}
          <div className="bg-white rounded-lg shadow-md p-6">
            <h2 className="text-xl font-bold text-gray-900 mb-4">User Input</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label htmlFor="growthStage" className="block text-sm font-medium text-gray-700 mb-2">
                  Paddy Growth Stage
                </label>
                <select
                  id="growthStage"
                  value={growthStage}
                  onChange={(e) => setGrowthStage(e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-agri-green-500 focus:border-agri-green-500"
                >
                  <option value="">Select growth stage</option>
                  {growthStages.map((stage) => (
                    <option key={stage} value={stage}>
                      {stage}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label htmlFor="purpose" className="block text-sm font-medium text-gray-700 mb-2">
                  Fertilizer Purpose
                </label>
                <select
                  id="purpose"
                  value={purpose}
                  onChange={(e) => setPurpose(e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-agri-green-500 focus:border-agri-green-500"
                >
                  <option value="">Select purpose</option>
                  {purposes.map((p) => (
                    <option key={p} value={p}>
                      {p}
                    </option>
                  ))}
                </select>
              </div>
            </div>
          </div>

          {/* 4. Action Button */}
          <div className="bg-white rounded-lg shadow-md p-6">
            <button
              onClick={handleGenerateRecommendation}
              disabled={loading || !canGenerate}
              className="w-full bg-agri-green-600 text-white py-3 px-6 rounded-lg font-semibold text-lg hover:bg-agri-green-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? 'Generating Recommendation...' : 'Generate Fertilizer Recommendation'}
            </button>
          </div>

          {/* 5. Recommendation Output Section */}
          {results && (
            <div className="bg-white rounded-lg shadow-md p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-bold text-gray-900">Top 3 Fertilizer Recommendations</h2>
                <div className="flex items-center space-x-3">
                  {saved && (
                    <span className="text-sm text-green-600 font-medium flex items-center">
                      <span className="mr-1">✓</span> Saved to history
                    </span>
                  )}
                  <button
                    onClick={handleSavePrediction}
                    className="bg-purple-600 text-white px-4 py-2 rounded-lg font-medium hover:bg-purple-700 transition-colors flex items-center space-x-2"
                  >
                    <span>💾</span>
                    <span>Save</span>
                  </button>
                  <button
                    onClick={() => handleDownloadReport()}
                    className="bg-blue-600 text-white px-4 py-2 rounded-lg font-medium hover:bg-blue-700 transition-colors flex items-center space-x-2"
                  >
                    <span>📥</span>
                    <span>Download Report</span>
                  </button>
                </div>
              </div>
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Rank
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Fertilizer Name
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Quantity (kg/acre)
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Predicted Yield (ton/ha)
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Confidence (%)
                      </th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {results.top3.map((item) => (
                      <tr
                        key={item.rank}
                        className={item.rank === 1 ? 'bg-agri-green-50' : 'hover:bg-gray-50'}
                      >
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className="w-8 h-8 bg-agri-green-600 text-white rounded-full flex items-center justify-center font-bold text-sm">
                            {item.rank}
                          </span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-semibold text-gray-900">
                          {item.fertilizer}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-700">{item.quantity}</td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-700">{item.predictedYield}</td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-700">{item.confidence}%</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* 6. Visualization Section */}
          {results && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Bar Chart: Fertilizer vs Predicted Yield */}
              <div className="bg-white rounded-lg shadow-md p-6">
                <h2 className="text-xl font-bold text-gray-900 mb-4">Fertilizer vs Predicted Yield</h2>
                <ResponsiveContainer width="100%" height={300}>
                  <BarChart data={barChartData}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="fertilizer" />
                    <YAxis />
                    <Tooltip />
                    <Legend />
                    <Bar dataKey="yield" fill="#22c55e" name="Predicted Yield (ton/ha)" radius={[8, 8, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>

              {/* Doughnut Chart: Confidence Distribution */}
              <div className="bg-white rounded-lg shadow-md p-6">
                <h2 className="text-xl font-bold text-gray-900 mb-4">Confidence Distribution</h2>
                <ResponsiveContainer width="100%" height={300}>
                  <PieChart>
                    <Pie
                      data={confidenceData}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={100}
                      paddingAngle={5}
                      dataKey="value"
                      label={({ name, value }) => `${name}: ${value}%`}
                    >
                      {confidenceData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip />
                    <Legend />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}

          {/* 7. Advisory / Sustainability Note */}
          {results && (
            <div className="bg-white rounded-lg shadow-md p-6">
              <h2 className="text-xl font-bold text-gray-900 mb-4">Advisory Note</h2>
              <div className="bg-agri-green-50 border-l-4 border-agri-green-500 p-6 rounded-lg">
                <p className="text-gray-700 leading-relaxed">
                  <strong>Optimized Fertilizer Usage Recommendation:</strong> Based on the{' '}
                  {sensorMode ? 'current sensor readings' : 'manually entered sensor values'} and
                  your selected growth stage and purpose, the recommended fertilizer application will help optimize crop
                  yield while maintaining soil health and sustainability. The top-ranked recommendation (Rank 1) has been
                  selected based on the highest confidence score and predicted yield. It is recommended to apply the
                  fertilizer at the specified quantity (kg/acre) during the current growth stage for optimal results.
                  Regular monitoring of soil conditions and adjusting fertilizer application based on{' '}
                  {sensorMode ? 'real-time sensor data' : 'accurate manual measurements'} will
                  ensure sustainable farming practices and maximize crop productivity.
                </p>
              </div>
            </div>
          )}
        </>
      )}

      {/* History Tab Content */}
      {activeTab === 'history' && (
        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl font-bold text-gray-900">Prediction History</h2>
            <p className="text-sm text-gray-600">
              {history.length === 0 ? 'No records found' : `${history.length} record(s) found`}
            </p>
          </div>

          {history.length === 0 ? (
            <div className="text-center py-12">
              <div className="text-6xl mb-4">📋</div>
              <p className="text-gray-600 text-lg">No prediction history available</p>
              <p className="text-gray-500 text-sm mt-2">
                Generate a recommendation and save it to see it here
              </p>
            </div>
          ) : (
            <div className="space-y-6">
              {history.map((record) => (
                <div key={record.id} className="border border-gray-200 rounded-lg p-6 hover:shadow-md transition-shadow">
                  <div className="flex items-start justify-between mb-4">
                    <div>
                      <div className="flex items-center space-x-3 mb-2">
                        <h3 className="text-lg font-bold text-gray-900">Prediction Record</h3>
                        <span className={`text-xs px-2 py-1 rounded ${
                          record.sensorMode === 'real-time' 
                            ? 'bg-green-100 text-green-800' 
                            : 'bg-blue-100 text-blue-800'
                        }`}>
                          {record.sensorMode === 'real-time' ? 'Real-time' : 'Manual'}
                        </span>
                      </div>
                      <p className="text-sm text-gray-600">
                        <span className="font-medium">Date:</span> {record.date} at {record.time}
                      </p>
                    </div>
                    <button
                      onClick={() => handleDownloadReport(record)}
                      className="bg-blue-600 text-white px-4 py-2 rounded-lg font-medium hover:bg-blue-700 transition-colors flex items-center space-x-2"
                    >
                      <span>📥</span>
                      <span>Download</span>
                    </button>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-4">
                    <div>
                      <h4 className="text-sm font-semibold text-gray-700 mb-2">Sensor Data</h4>
                      <div className="bg-gray-50 rounded-lg p-3 space-y-1 text-sm">
                        <div className="flex justify-between">
                          <span className="text-gray-600">Soil Temperature:</span>
                          <span className="font-medium">{record.sensorData.soilTemperature}°C</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-600">Soil Moisture:</span>
                          <span className="font-medium">{record.sensorData.soilMoisture}%</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-600">Air Temperature:</span>
                          <span className="font-medium">{record.sensorData.airTemperature}°C</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-600">Air Humidity:</span>
                          <span className="font-medium">{record.sensorData.airHumidity}%</span>
                        </div>
                      </div>
                    </div>

                    <div>
                      <h4 className="text-sm font-semibold text-gray-700 mb-2">User Input</h4>
                      <div className="bg-gray-50 rounded-lg p-3 space-y-1 text-sm">
                        <div className="flex justify-between">
                          <span className="text-gray-600">Growth Stage:</span>
                          <span className="font-medium">{record.userInput.growthStage}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-600">Purpose:</span>
                          <span className="font-medium">{record.userInput.purpose}</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div>
                    <h4 className="text-sm font-semibold text-gray-700 mb-3">Recommendations</h4>
                    <div className="overflow-x-auto">
                      <table className="min-w-full divide-y divide-gray-200">
                        <thead className="bg-gray-50">
                          <tr>
                            <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Rank</th>
                            <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Fertilizer</th>
                            <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Quantity</th>
                            <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Yield</th>
                            <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Confidence</th>
                          </tr>
                        </thead>
                        <tbody className="bg-white divide-y divide-gray-200">
                          {record.recommendations.map((item) => (
                            <tr key={item.rank} className={item.rank === 1 ? 'bg-agri-green-50' : ''}>
                              <td className="px-4 py-2 whitespace-nowrap text-sm">
                                <span className="w-6 h-6 bg-agri-green-600 text-white rounded-full flex items-center justify-center font-bold text-xs">
                                  {item.rank}
                                </span>
                              </td>
                              <td className="px-4 py-2 whitespace-nowrap text-sm font-semibold">{item.fertilizer}</td>
                              <td className="px-4 py-2 whitespace-nowrap text-sm">{item.quantity} kg/acre</td>
                              <td className="px-4 py-2 whitespace-nowrap text-sm">{item.predictedYield} ton/ha</td>
                              <td className="px-4 py-2 whitespace-nowrap text-sm">{item.confidence}%</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  )
}
